name: build

on:
  push:
    branches:
      - "main"

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: v2.2.0
          go_version: 1.19
          dest: dist
          prefix: daycatapi
          targets: linux/amd64,linux/arm64,darwin/arm64, darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist