# workflow name
name: Build

# on events
on:
  push:
    branches:
      - 'main'


      # workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build files
        uses: tobyxdd/go-cross-build@d00fc41eb205f57dd90f6e5af4613e21c7ebe73f
        with:
          platforms: 'linux/amd64,linux/arm,linux/arm64,linux/s390x'
          name: 'daycatapi'
          compress: 'false'
          dest: 'dist'
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist